# Site settings
title: PNT_bio
description: My Bio
baseurl: "" # Leave this empty for GitHub Pages root-level deployment
url: "https://artech011100000110111001110100.github.io" # Replace with your GitHub Pages URL

# Markdown processing
markdown: kramdown # Default Markdown engine
highlighter: rouge
kramdown:
  input: GFM # GitHub Flavored Markdown
  auto_ids: true
  toc_levels: 1..6

# Collections
collections:
  posts:
    output: true # Enable posts to be converted to HTML
  drafts:
    output: false # Drafts are not published unless explicitly enabled

# Permalinks for posts
permalink: /:title/

# Defaults for files
defaults:
  - scope:
      path: "" # All files
    values:
      layout: "default"

# Exclude files and directories from being processed
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle